---
title: "Assignment2_RuijiaLiang"
author: "Ruijia Liang u7457322"
date: "`r Sys.Date()`"
output: 
  bookdown::html_document2:
    code_folding: show
    number_sections: no
    toc: yes
    toc_depth: 6
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries, echo=FALSE, include=TRUE, message=FALSE, warning=FALSE}
library(pacman)
p_load(bookdown, devtools, tidyverse, ggforce, GGally, flextable, latex2exp, png, magick, metafor, MASS, emmeans, R.rsp, orchaRd, pander, mathjaxr, equatags, vembedr,data.table)
```

# Preparation before analysing

```{r load the data, echo = FALSE, results = 'hide', warning=FALSE, error=FALSE, message=FALSE}
raw_data <- read_csv("./data/OA_activitydat_20190302_BIOL3207.csv")

paper_data <- read_csv("./data/clark_paper_data.csv")

meta_data <- read_csv("./data/ocean_meta_data.csv")
```


```{r remove NA}
raw_data <- raw_data[complete.cases(raw_data),]
```


```{r convert into factors}
raw_data$species <- factor(raw_data$species)
raw_data$treatment <- factor(raw_data$treatment)
```


# Generate the summary statistics


```{r get N and sd and means}
get_statistics <- function(species_name){
  t_species_data <- raw_data %>% filter(species==species_name,treatment=="CO2")
  c_species_data <- raw_data %>% filter(species==species_name,treatment=="control")

  species_statistics <- data.frame(Species = character(), ctrl.n = numeric(), ctrl.mean=numeric(), ctrl.sd = numeric(), oa.n=numeric(), oa.mean = numeric(), oa.sd = numeric())
  
  species_statistics[1,1] <- species_name
  species_statistics[1,2] <- length(c_species_data$activity)
  species_statistics[1,3] <- mean(c_species_data$activity)
  species_statistics[1,4] <- sd(c_species_data$activity)
  species_statistics[1,5] <- length(t_species_data$activity)
  species_statistics[1,6] <- mean(t_species_data$activity)
  species_statistics[1,7] <- sd(t_species_data$activity)

  return(species_statistics)
}
```


```{r make a summary table}
summary_table <- rbind(get_statistics("acantho"),get_statistics("ambon"),get_statistics("chromis"),get_statistics("humbug"),get_statistics("lemon"),get_statistics("whitedams"))
flextable(summary_table) %>% add_header_lines(.,values = "Summary of data")
```



# Merge the summary statistics with the clark_paper_data


```{r combine the dataframes}
sp_data <- cbind(paper_data,summary_table)
```


# Merge the sp_data with the meta_data


```{r combine the dataframes again}
data <- rbind(sp_data,meta_data)
```









